# ----------------------------------------
# Created on: Wed Oct 11 22:00:37 2023
# Auto generated by Pango
# ----------------------------------------

# vsim  -voptargs=+acc  -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_top usim.GTP_GRS
vsim  -voptargs=+acc work.tb_top
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
