#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Oct 11 21:31:32 2023

remove_design -verilog "C:/Users/WS/Desktop/SoC/E203_SoC/E203_RTL/tb/tb_top.v"
remove_design -verilog "C:/Users/WS/Desktop/SoC/E203_SoC/E203_RTL/system.v"
add_simulation "C:/Users/WS/Desktop/SoC/E203_SoC/E203_RTL/tb/tb_top.v"
